api_version: 1
threadsafe: yes
service: hello-nodejs
runtime: nodejs
env: flex
env_variables:
  GCLOUD_STORAGE_BUCKET: gs://nodejs-app
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10